// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Movies_Project
{
    public partial class MovieRecommenderModel
    {
        /// <summary>
        /// model input class for MovieRecommenderModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"index")]
            public float Index { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"budget")]
            public float Budget { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"genres")]
            public string Genres { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"homepage")]
            public string Homepage { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"id")]
            public float Id { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"keywords")]
            public string Keywords { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"original_language")]
            public string Original_language { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"original_title")]
            public string Original_title { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"overview")]
            public string Overview { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"popularity")]
            public string Popularity { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"production_companies")]
            public string Production_companies { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"production_countries")]
            public string Production_countries { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"release_date")]
            public string Release_date { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"revenue")]
            public string Revenue { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"runtime")]
            public string Runtime { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"spoken_languages")]
            public string Spoken_languages { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"status")]
            public string Status { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"tagline")]
            public string Tagline { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"title")]
            public string Title { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"vote_average")]
            public string Vote_average { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"vote_count")]
            public string Vote_count { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"cast")]
            public string Cast { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"crew")]
            public string Crew { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"director")]
            public string Director { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MovieRecommenderModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"index")]
            public float Index { get; set; }

            [ColumnName(@"budget")]
            public float Budget { get; set; }

            [ColumnName(@"genres")]
            public float[] Genres { get; set; }

            [ColumnName(@"homepage")]
            public float[] Homepage { get; set; }

            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"keywords")]
            public float[] Keywords { get; set; }

            [ColumnName(@"original_language")]
            public float[] Original_language { get; set; }

            [ColumnName(@"original_title")]
            public float[] Original_title { get; set; }

            [ColumnName(@"overview")]
            public float[] Overview { get; set; }

            [ColumnName(@"popularity")]
            public float[] Popularity { get; set; }

            [ColumnName(@"production_companies")]
            public float[] Production_companies { get; set; }

            [ColumnName(@"production_countries")]
            public float[] Production_countries { get; set; }

            [ColumnName(@"release_date")]
            public float[] Release_date { get; set; }

            [ColumnName(@"revenue")]
            public float[] Revenue { get; set; }

            [ColumnName(@"runtime")]
            public float[] Runtime { get; set; }

            [ColumnName(@"spoken_languages")]
            public float[] Spoken_languages { get; set; }

            [ColumnName(@"status")]
            public float[] Status { get; set; }

            [ColumnName(@"tagline")]
            public float[] Tagline { get; set; }

            [ColumnName(@"title")]
            public float[] Title { get; set; }

            [ColumnName(@"vote_average")]
            public float[] Vote_average { get; set; }

            [ColumnName(@"vote_count")]
            public float[] Vote_count { get; set; }

            [ColumnName(@"cast")]
            public float[] Cast { get; set; }

            [ColumnName(@"crew")]
            public float[] Crew { get; set; }

            [ColumnName(@"director")]
            public float[] Director { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MovieRecommenderModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
